### ISSUE TITLE
Deletion of a domain fails if there is contact request record in the whois db

### ISSUE THREAD

**Issue by vohmar** [internetee/rest-whois#103]
If at any point in time someone has attempted to contact private registrant using contact request procedure the release of that domain name registration fails because of failed attempt to delete the record in whois db

`ERROR:  update or delete on table "whois_records" violates foreign key constraint "fk_rails_6af241b4ac" on table "contact_requests"`

**Comment by maciej-szlosarczyk** [comment]
A few gothchas for the fix:

- When a domain is deleted, orphaned contact requests continue to exist in database
- In the UI, a contact request for deleted domain should behave the same way as one that has already expired or used: return 404.
