### ISSUE TITLE
No emails sent if any of the email addresses of domain contacts is invalid

### ISSUE THREAD

**Issue by vohmar** [internetee/rest-whois#113]
In contact registrant form there is an option to send the letter to registrant and admin contact, and/or technical contact. If any of the contacts selected have invalid email address no one gets the letter.

Expected results is that all valid email addresses get the letter and invalid attempts are properly logged.

**Comment by maciej-szlosarczyk** [comment]
This is not up to the web application. Web application passes an array of addresses to the SMTP server, it's up to that server to handle it gracefully.

**Comment by vohmar** [comment]
@teadur can we solve this on email server side?

**Comment by vohmar** [comment]
solved by reconfiguring mail server - valid emails do get the email now, but invlaid addresses bounce and thus no error message is sent back to registry server. . Will try to solve the user feedback in separate ticket.
