### ISSUE TITLE
Nothing is logged on failed email attempt

### ISSUE THREAD

**Issue by vohmar** [internetee/rest-whois#115]
Email server is configured to bounce the emails back to from address in case sending the email to intended address failed. Because of this no error is logged and user gets not feedback if there is a problem.

To solve this and save time we should consider using third party service for sending emails. Services like 

* Mandrill
* Postmark 
* Amazon Simple Email Service

**Comment by yulgolem** [comment]
@timo BTW found this approach - https://corgibytes.com/blog/2017/01/31/aws-ses-sns/
Maybe it could help us a bit.

In two words - it describes the creation of a standalone service processing bounce callbacks from Amazon SES. Maybe our email service could send us bounce callbacks as well? Or maybe we should use Amazon?

Also the question is - if we would use this callback approach, should we use it in one single app or should we create a dedicated service for all the apps?

**Comment by yulgolem** [comment]
Also without any Amazon SES, purely system design point of view - https://stackoverflow.com/a/8503924

**Comment by yulgolem** [comment]
Also on Postmark (https://github.com/wildbit/postmark-rails), if we don't want to delve deep into our SMTP relay configuration. And yes, they API got a bounce control endpoint.
