### ISSUE TITLE
Missing translations for language selection in web view

### ISSUE THREAD

**Issue by vohmar** [internetee/rest-whois#119]
Language selection in top left of the screen:
http://staging.infra.tld.ee/?locale=et
http://staging.infra.tld.ee/?locale=ru
http://staging.infra.tld.ee/v1/timo-9k.ee?locale=et
http://staging.infra.tld.ee/v1/timo-9k.ee?locale=ru
http://staging.infra.tld.ee/contact_requests/new?domain_name=timo-9k.ee&locale=et
http://staging.infra.tld.ee/contact_requests/new?domain_name=timo-9k.ee&locale=ru

alse the contact form

ie in every view with the language selection option.

**Comment by artur-beljajev** [comment]
Same on prod https://rwhois.internet.ee/?locale=ru.
