### ISSUE TITLE
Remove unused `whois_records.body` column

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/rest-whois#131]

**Comment by artur-beljajev** [comment]
> body is not used be neither web whois nor the command-line one. It was used, and there was some on-the-fly filling in the disclosed parts in the body from json disclosed field, but I changed that in May because it would not work with more complex GDPR logic.

https://github.com/internetee/whois/pull/27/files
https://github.com/internetee/rest-whois/pull/41/files

**Comment by vohmar** [comment]
blocked by https://github.com/internetee/registry/pull/1037 (merge conflicts)
