### ISSUE TITLE
Actionvew security update

### ISSUE THREAD

**Issue by vohmar** [internetee/rest-whois#219]
https://github.com/internetee/rest-whois/network/alert/Gemfile.lock/actionview/open

dependabot is not able to create the pr automatically.

One other thing I noticed is that rest-whois uses actionview v5 while auction is using v6 is there a reason for that or would it be possible to upgrade this to v6 as well?

**Comment by yulgolem** [comment]
The main issue here is auction app uses rails 6 (which depends on actionview) and, say, registry is using rails 5.1 which depends on actionview 5.1.7, so in order to raise actionview we need to raise rails version.
