### ISSUE TITLE
Recaptcha is not available

### ISSUE THREAD

**Issue by vohmar** [internetee/rest-whois#262]
Recaptcha is not shown to user on test and production environments 

error:
Refused to frame 'https://www.recaptcha.net/' because it violates the following Content Security Policy directive: "frame-src 'self' https://www.google.com/recaptcha/".

and from firefox:
Content Security Policy: The page’s settings blocked the loading of a resource at https://www.recaptcha.net/recaptcha/api2/anchor?ar=1&k=6Ld-ARETAAAAAPN1pcTy9oYsUrbKm9_c9VDMvl6X&co=aHR0cDovL3dob2lzLmVlOjgw&hl=en&v=f-bnnOuahiYKuei7dmAd3kgv&size=normal&cb=iyifhngxe0tb (“frame-src”).

possible solution: https://stackoverflow.com/questions/39853162/recaptcha-with-content-security-policy

**Comment by yulgolem** [comment]
Maybe we should consider upgrading this to RECAPCHA 3 or something like that.

**Comment by yulgolem** [comment]
Upgrading to recaptcha 3 should be made via separate task/PR
