### ISSUE TITLE
Disputed status

### ISSUE THREAD

**Issue by vohmar** [internetee/rest-whois#29]
whois must return status "disputed" for domains that are in dispute domains list but are not registered any more (similarly to reserved and blocked domains).

subtask to: https://github.com/internetee/registry/issues/269

**Comment by vohmar** [comment]
* record with disputed status is generated in whois db only if domain is not registered (not in domains table)
* if disputed domain is registered, it is removed from the disputed list in registry, so the disputed record must be removed from the whois db and replaced with regular registered domain record
* if dispute is expired, the domain is removed from disputed list in registry, so the disputed record must be removed from whois db as well
* if domain in disputed list is simultaneously in reserved list and is not registered the record in whois db must reflect both statuses - reserved, disputed
* if domain in both reserved and disputed list is removed from disputed list due to expiry the record with both statuses must be replaced with only reserved status
* if domain in both lists is registered, the previous whois record must be removed and replaced with regular registered domain record

**Comment by artur-beljajev** [comment]
#375

**Comment by artur-beljajev** [comment]
unregistered, disputed, reserved = whois: reserved, disputed

**Comment by vohmar** [comment]
not to forget that disputed domains are usually registered and can be reserved as well - so a domain can have all the states (registered, reserved, disputed) simultaneously.
