### ISSUE TITLE
Add IPv6 support to special access allow-list

### ISSUE THREAD

**Issue by vohmar** [internetee/rest-whois#326]
We have allow list for ip addresses that will receive complete set of data as a response to whois request for law-enforcement agencies. This list supports only ipv4 addresses at the moment. One of our partners has requested for IPv6 support -  they are upgrading their own systems and would like to avoid using ipv4 

Testing:
* add ipv6 address to the allow list
* request registered domain data via rest-whois api
* check if the response includes all details of business and private contacts including their contact information (email and phone nr)

**Comment by maricavor** [comment]
Tested by adding ipv6 address to whitelist and simulating request with the same ipv6 address:
`request = ActionDispatch::Request.new('REMOTE_ADDR' => '2001:4860:4860:0000:0000:0000:0000:8888')`
`ip = request.remote_ip`
`whitelist.include?(ip)`

Method ip_in_whitelist? and functionality works the same way as with ipv4 addresses. Just add ipv6 address to whitelist:
`whitelist_ip: '127.0.0.1, 127.0.0.2, 2001:4860:4860:0000:0000:0000:0000:8888'`

**Comment by ratM1n** [comment]
Works.
