### ISSUE TITLE
Why is mail gem included

### ISSUE THREAD

**Issue by teadur** [internetee/rest-whois#35]
As of the rest-whois doesnot send any emails, why is the mail gem included ?

**Comment by artur-beljajev** [comment]
You mean updated? Because it is listed here https://gemnasium.com/github.com/internetee/rest-whois/alerts. "mail" gem is a dependency of "action_mailer" gem, which it turn a dependency of "rails" gem.

**Comment by teadur** [comment]
Okey, thanks for quick reply.
