### ISSUE TITLE
Remove any reference of UNIX body in REST WHOIS

### ISSUE THREAD

**Issue by maciej-szlosarczyk** [internetee/rest-whois#40]
For whois display on HTML pages, we traverse each line of the body and add/remove disclosed emails. It is:

- Not very efficient
- Not readable either

We should use only JSON data for creating web whois records.

https://github.com/internetee/rest-whois/blob/master/app/models/whois_record.rb#L12-L23

**Comment by vohmar** [comment]
agreed

**Comment by maciej-szlosarczyk** [comment]
Fixed with #41, can be closed.
