### ISSUE TITLE
Improve error handling in contact request functionality

### ISSUE THREAD

**Issue by maciej-szlosarczyk** [internetee/rest-whois#53]
- [ ] More descriptive errors for used/expired `secret` tokens. Fixed in #86 
- [x] ~Better communicating of errors in SMTP functionality.~ Cannot be reproduced any more.

**Comment by maciej-szlosarczyk** [comment]
I assume that is a configuration issue. Locally, even a made up and clearly invalid email produces the following result:

![kapture 2018-06-11 at 13 12 43](https://user-images.githubusercontent.com/2331765/41226229-8d76dda2-6d79-11e8-97ef-8d267c752b63.gif)

![screen shot 2018-06-11 at 13 13 50](https://user-images.githubusercontent.com/2331765/41226253-9b6521a8-6d79-11e8-80d6-8d4512d4db70.png)

**Comment by vohmar** [comment]
current master version produces this result in test and production (used the same email address you did in your example):

![image](https://user-images.githubusercontent.com/7734747/41284835-274a4dd2-6e43-11e8-9858-865d4a48c1a2.png)

**Comment by teadur** [comment]
Users have reported invalid email address exception aswell: 
One example from logs:


Jun 27 22:13:53 reg-l-whois rest-whois[15540]: Confirmation email sent to broken@email.e.
Jun 27 22:13:54 reg-l-whois rest-whois[15540]: 
Jun 27 22:13:54 reg-l-whois rest-whois[15540]: Net::SMTPServerBusy (450 4.1.2 <broken@email.e>: Recipient address rejected: Domain not found#012):
Jun 27 22:13:54 reg-l-whois rest-whois[15540]: 
Jun 27 22:13:54 reg-l-whois rest-whois[15540]: app/models/contact_request.rb:30:in `send_confirmation_email'#012app/controllers/contact_requests_controller.rb:16:in `create'

This should be handled more gracefuly

**Comment by maciej-szlosarczyk** [comment]
Now that I know what's the actual exception, I'll add the handling to it 👍

**Comment by maciej-szlosarczyk** [comment]
Fix is available with #106 

I'd need better UI text for the rescue messages:

```
en: SMTP server error. Please check your email address and try again.
et: SMTP serveri viga. Palun kontrollige oma e-posti aadress ja proovi uuesti.
ru: missing
```

**Comment by vohmar** [comment]
I would simplify the message a bit - smtp might be too technical term :
en: Email confirmation failed. Please check your email address and try again.
et: E-posti aadressi kinnitamine ebaõnnestus. Palun kontrollige oma e-posti aadressi ja proovige uuesti.
ru: Не удалось подтвердить подтверждение по электронной почте. Проверьте свой адрес электронной почты и повторите попытку.

**Comment by maciej-szlosarczyk** [comment]
Text is updated now in `catch-smtp-errors` branch.

**Comment by vohmar** [comment]
the expeptions do not reach the user any more

log:
```
Jun 29 15:31:37 test-reg rest-whois[14375]: Confirmation email sent to a@b.c.
Jun 29 15:31:37 test-reg rest-whois[14375]: 
Jun 29 15:31:37 test-reg rest-whois[14375]: Net::SMTPServerBusy (450 4.1.2 a@b.c: Recipient address rejected: Domain not found#012):
Jun 29 15:31:37 test-reg rest-whois[14375]: 
Jun 29 15:31:37 test-reg rest-whois[14375]: app/models/contact_request.rb:30:in send_confirmation_email'#012app/controllers/contact_requests_controller.rb:16:increate'
```
UI forwards user to the search view just like in the case of success.
if the email is not sent user should get notified.

**Comment by vohmar** [comment]
fantom recaptcha verification error
1. http://staging.infra.tld.ee/ and search for a domain timo-9k2.ee
2. http://staging.infra.tld.ee/v1/timo-9k2.ee - the page returns instantly "reCAPTCHA verification failed, please try again." error message
3. solving recaptcha returns additional info or gives an option to contact registrant, but the reCaptcha error message does not go away
4. http://staging.infra.tld.ee/contact_requests/new?domain_name=timo-9k2.ee&locale=en - recaptcha error message is still there

**Comment by maciej-szlosarczyk** [comment]
The error is always there, it's related to expecting captcha with GET requests as well. Now it should be hidden.

**Comment by maciej-szlosarczyk** [comment]
There is no reason to do that. If we treat this as a validation error and/or user mistake, then we shouldn't bother about it at all. Similarly we don't bother all the users that do not make it past the browser validation:

![image](https://user-images.githubusercontent.com/2331765/42202193-2f26d1a4-7ea3-11e8-8a8c-3af575b3f0b1.png)

**Comment by teadur** [comment]
I'm just thinking of sitsuation someone claims they used the contact form to contact the owner and now i'm told to check if the email was sent or not.
I first have to check the application log for the email / time and then i have to check the mailserver log to see if the email was actualy sent or not because application always logs confirmation email sent.

I wouldnot compare it to 1-1 with browser validation (and we do log that :)).

**Comment by maciej-szlosarczyk** [comment]
> I'm just thinking of sitsuation someone claims they used the contact form to contact the owner and now i'm told to check if the email was sent or not.
I first have to check the application log for the email / time and then i have to check the mailserver log to see if the email was actualy sent or not because application always logs confirmation email sent.

This is not applicable to emails being sent to domain contacts, those will fail as they did previously. And they should as that would mean that one of the contacts in domain records has an incorrect email (which is a problem for as TLD, not for the user). 

As a user, if instead of `maciej.szlosarczyk@internet.ee` I enter `maciej.szlosarczyk@internet.e`, I get a big banner saying that something went wrong. We can work with the text if it's confusing.

![image](https://user-images.githubusercontent.com/2331765/42202979-0fa35c6e-7ea6-11e8-9833-b4e1fb39926d.png)

> I wouldnot compare it to 1-1 with browser validation (and we do log that :)).

This is not a Javascript exception nor the ActiveRecord validation. This is the browser telling me that an email address should look like an email. There's no network request dispatch from the client, so it's impossible for us to log that.

**Comment by teadur** [comment]
The problem for me is that i cannot differentiate email confirmation sent and email confirmation failed from system logs.

Only user gets the error email confirmation failed.

**Comment by maciej-szlosarczyk** [comment]
>The problem for me is that i cannot differentiate email confirmation sent and email confirmation failed from system logs.
Only user gets the error email confirmation failed.

From the perspective of the web application, the email is sent. It went to the queue and was passed to the SMTP server, which handles the actual delivery. If we were using Gmail or some other third-party mass-sending software (Sendgrid, Mailgun, Mandrill), we won't see the `Net::SMTPServerBusy` errors at all, it would just go through. You'd have to look into that service web interface or you'd get a return email telling you that something went wrong.

I added an additional log message in `log-more-messages` branch, please test if that's what you want. I have no way of testing it locally. However, this is a flawed practice. We shouldn't bring concerns from the specific SMTP server we are using to the web application.

**Comment by vohmar** [comment]
SMTP errors on sending the letter to actual domain contacts are still not handled - user gets error 500 if any of the contact email addresses is invalid. Should be handled more gracefully. These errors are important to catch as well to be able to start the data quality improvement process by letting registrar know of invalid data.

**Comment by maciej-szlosarczyk** [comment]
> SMTP errors on sending the letter to actual domain contacts are still not handled - user gets error 500 if any of the contact email addresses is invalid. Should be handled more gracefully. 

This is expected behaviour. We should not rescue errors that come from incorrect data in the database, it's our error, quite a bad one at that.

> These errors are important to catch as well to be able to start the data quality improvement process by letting registrar know of invalid data.

Unless we are greping logs in search for errors, every invalid request like that should produce an error in Errbit/Airbrake.
