### ISSUE TITLE
Add search by domain name

### ISSUE THREAD

**Issue by maciej-szlosarczyk** [internetee/rest-whois#64]
If we want to redirect more traffic to REST WHOIS, we need a search feature, where you can find info about a domain. Currently it is only available as a parameter in the URL.

**Comment by vohmar** [comment]
translations to estonian:
search = otsi
search_by_domain_name = otsi domeeninimega
domain_name = domeeninimi

**Comment by vohmar** [comment]
how do I test this? how to access the search feature?

**Comment by maciej-szlosarczyk** [comment]
Fixed with #77
