### ISSUE TITLE
Consider sending localized emails, instead of mix of all languages.

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/rest-whois#91]
Given there is a language selector in UI, I don't see the point sending multilingual emails.

Probably requires some integration with Voog.

**Comment by maciej-szlosarczyk** [comment]
That only applies to one email. The emails that are sent to the domain contacts need to be in 3 languages, as we cannot infer what language the domain owner speaks from the WhoisRecord.

**Comment by maciej-szlosarczyk** [comment]
Fixed with #97

**Comment by vohmar** [comment]
in production
